### PR TITLE
fix(dapp): export decoded votes

### LINKED ISSUE #73: Export decoded votes
We want to have a button to be able to save the data in CSV after having decoded anonymous votes.

Add a clear warning when clicking on the button asking for confirmation and saying that this has an impact on the privacy of the voters if the file is shared online or leaks.

Image

### PR DESCRIPTION
**Pull request by Shadow-MMN**
- Adds an export button for decoded anonymous votes with a confirmation modal and a clear privacy warning before downloading CSV.
- Reuses the app’s existing modal pattern for the confirmation step.
- Improves the anonymous vote UI copy to clarify that final outcomes are based on weighted tallies, which can still lead to cancelled even when raw approve counts are higher.
- Tightens contract error messaging for finalize/execute failures so transfer() simulation errors point at the configured outcome contract inputs.
- Updates `dapp/astro.config.mjs` to explicitly include `ipfs-car` in `Vite optimizeDeps`. This was needed because project/proposal creation lazy-loads `ipfs-car`, and the dev server was failing to fetch the generated Vite chunk for it. Prebundling it makes the browser import stable during local development.

Current Implementation looks like this 
Screenshot 2026-04-25 at 21 19 00
----------------------------------
Screenshot 2026-04-25 at 21 15 50

Closes #73

### CODE REVIEW

**Comment by tupui** [comment]
Thanks I will try it out soon

File: dapp/src/components/page/proposal/ExportDecodedVotesModal.tsx [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+        <Title
+          title="Export decoded votes"
+          description="This exports the decrypted ballot rows as a CSV file."
+        />
+
+        <div className="rounded-lg border border-red-200 bg-red-50 p-4 sm:p-5 text-sm sm:text-base text-primary">
+          <p className="font-medium text-red-700">Privacy warning</p>
+          <p className="mt-2 leading-6">
+            Decoded votes reveal who voted for what. If this file is shared
+            online, forwarded, or leaked, voter privacy is lost.
```
Comment (tupui) [inline dapp/src/components/page/proposal/ExportDecodedVotesModal.tsx]:
```suggestion
            Decoded votes reveal who voted for what. If this file is shared
            online, forwarded, or leaked, the voter privacy assumption is lost.
```

File: dapp/src/components/page/proposal/ExportDecodedVotesModal.tsx [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+          </p>
+          <p className="mt-2 leading-6">
+            Only export this file if you are sure it will stay private.
```
Comment (tupui) [inline dapp/src/components/page/proposal/ExportDecodedVotesModal.tsx]:
```suggestion
            Only export this file if you can assume the responsibility
            of keeping voters' information private.
```

File: dapp/src/components/page/proposal/ExecuteProposalModal.tsx [hunk 3]
```diff
@@ -285,6 +286,10 @@ const ExecuteProposalModal: React.FC<ExecuteProposalModalProps> = ({
                 decodedVotes={decodedVotes}
                 proofOk={proofOk}
                 proofErrorMessage={proofErrorMessage}
+                exportFileNameBase={`${projectName.replace(
+                  /[^a-z0-9_-]+/gi,
+                  "-",
+                )}-proposal-${proposalId}-decoded-votes`}
```
Comment (tupui) [inline dapp/src/components/page/proposal/ExecuteProposalModal.tsx]:
```suggestion
                )}-proposal-${proposalId}-decoded-votes.csv`}
```

File: dapp/src/components/page/proposal/VerifyAnonymousVotesModal.tsx [hunk 4]
```diff
@@ -118,6 +119,10 @@ const VerifyAnonymousVotesModal: React.FC<Props> = ({
             decodedVotes={decodedVotes}
             proofOk={proofOk}
             proofErrorMessage={proofErrorMessage}
+            exportFileNameBase={`${projectName.replace(
+              /[^a-z0-9_-]+/gi,
+              "-",
+            )}-proposal-${proposalId}-decoded-votes`}
```
Comment (tupui) [inline dapp/src/components/page/proposal/VerifyAnonymousVotesModal.tsx]:
```suggestion
            )}-proposal-${proposalId}-decoded-votes.csv`}
```

File: dapp/src/components/page/proposal/AnonymousTalliesDisplay.tsx [hunk 5]
```diff
@@ -35,39 +42,53 @@ const AnonymousTalliesDisplay: React.FC<Props> = ({
...
+                  ))}
+                </tbody>
+              </table>
+            </div>
+          </details>
+
+          <div className="flex flex-col items-center justify-between gap-3 flex-wrap mt-3">
+            <p className="text-xs md:text-sm text-secondary max-w-prose">
+              Exporting decoded votes removes anonymity from the file. Keep it
+              private.
```
Comment (tupui) [inline dapp/src/components/page/proposal/AnonymousTalliesDisplay.tsx]:
```suggestion
              Exporting decoded votes compromise the privacy model.
```

File: dapp/src/components/page/proposal/AnonymousTalliesDisplay.tsx [hunk 6]
```diff
@@ -95,8 +116,21 @@ const AnonymousTalliesDisplay: React.FC<Props> = ({
             verification). Use it to confirm decrypted results before executing
             the proposal.
           </p>
+          <p className="text-xs md:text-sm text-secondary max-w-prose">
+            Final outcomes are based on weighted vote totals. A proposal can
+            still cancel if approvals do not exceed rejections plus abstentions
+            once weights are applied.
```
Comment (tupui) [inline dapp/src/components/page/proposal/AnonymousTalliesDisplay.tsx]:
```suggestion
            Final outcomes are based on weighted vote tallies. For a proposal
            to be accepted, the tally of approve votes must be higher than
            the sum of the tallies of reject plus cancel votes. Same goes to
            reject a proposal.
```

**Review by tupui — APPROVED** [review]
Nice this works as expected. I am just adjusting a bit the text to my liking.

**Comment by Shadow-MMN** [comment]
> Nice this works as expected. I am just adjusting a bit the text to my liking.

Ok

File: dapp/src/components/page/proposal/AnonymousTalliesDisplay.tsx [hunk 7]
```diff
@@ -35,39 +42,52 @@ const AnonymousTalliesDisplay: React.FC<Props> = ({
...
+                </tbody>
+              </table>
+            </div>
+          </details>
+
+          <div className="flex flex-col items-center justify-between gap-3 flex-wrap mt-3">
+            <p className="text-xs md:text-sm text-secondary max-w-prose">
+              Exporting decoded votes compromise the privacy model.
+            </p>
+            <Button
```
Comment (tupui) [inline dapp/src/components/page/proposal/AnonymousTalliesDisplay.tsx:79]:
```suggestion
          <div className="flex flex-col items-center justify-between gap-3 flex-wrap mt-3">
            <Button
```

File: dapp/src/components/page/proposal/ExportDecodedVotesModal.tsx [hunk 8]
```diff
@@ -0,0 +1,67 @@
...
+          </p>
+          <p className="mt-2 leading-6">
+            Only export this file if you can assume the responsibility
+            of keeping voters' information private.
+          </p>
+        </div>
+
+        <div className="flex flex-col gap-2 text-sm text-secondary">
+          <p>Rows to export: {decodedVotes.length}</p>
+          <p>Format: CSV</p>
```
Comment (tupui) [inline dapp/src/components/page/proposal/ExportDecodedVotesModal.tsx]:
```suggestion
          <p>Rows to export: {decodedVotes.length}</p>
```

File: dapp/src/components/page/proposal/VerifyAnonymousVotesModal.tsx [hunk 9]
```diff
@@ -118,6 +119,10 @@ const VerifyAnonymousVotesModal: React.FC<Props> = ({
             decodedVotes={decodedVotes}
             proofOk={proofOk}
             proofErrorMessage={proofErrorMessage}
+            exportFileNameBase={`${projectName.replace(
+              /[^a-z0-9_-]+/gi,
+              "-",
+            )}-proposal-${proposalId}-decoded-votes.csv`}
```
Comment (tupui) [inline dapp/src/components/page/proposal/VerifyAnonymousVotesModal.tsx]:
```suggestion
            )}-proposal-${proposalId}-decoded-votes`}
```
