### PR TITLE
fix: Show maintainer status in community engagement section

### LINKED ISSUE #64: Maintainer information in community engagement
Maintainers of projects should also see a badge in the community engagement section of their profil. E.g. in this case, that user is a maintainer on a project, yet not showing up here.

Image

See the project and check all users to see how it should look like.
https://testnet.tansu.dev/project/?name=stellarpg

### PR DESCRIPTION
**Pull request by Emmy123222**
- Add maintainer status detection in MemberProfileModal
- Display maintainer role as green status indicator (not a badge)
- Fetch projects where user is maintainer even without other badges
- Maintain separation between badges (community engagement) and maintainer role (admin status)
- Update noBadges logic to account for maintainer-only projects

Fixes issue where project maintainers were not seeing their maintainer status in the community engagement section of their profile.

Note: Maintainer status is shown as a role indicator, not as a badge, maintaining the distinction between badges (Developer, Triage, Community, Verified, Default) and administrative roles.

close #64

### CODE REVIEW

**Comment by Emmy123222** [comment]
@tupui  please review it

**Comment by tupui** [comment]
@Emmy123222 why did you close the other PR? Please don't do this in the future but simply update this one.

**Comment by Emmy123222** [comment]
> @Emmy123222 why did you close the other PR? Please don't do this in the future but simply update this one.

because i was facing some issues that why

File: dapp/src/components/page/dashboard/MemberProfileModal.tsx [hunk 1]
```diff
@@ -426,6 +466,13 @@ const MemberProfileModal: FC<Props> = ({ onClose, member, address }) => {
                               {badgeName(b)}
                             </span>
                           ))}
+                          {proj.isMaintainer && (
+                            <span
+                              className="px-2 py-0.5 sm:px-3 sm:py-1 bg-green-600 text-white text-xs sm:text-sm rounded font-medium"
```
Comment (tupui) [inline dapp/src/components/page/dashboard/MemberProfileModal.tsx]: Please use colours we defined in the CSS for our design system instead.

**Review by tupui — CHANGES_REQUESTED** [review]
Thanks, I checked and this looks nice. Please just fix the linters (there are commands with bun, etc. to help with that.)

**Comment by Emmy123222** [comment]
@tupui The Playwright E2E Tests  failure is an unrelated issue in the proposal/voting system that existed before  my  changes.

**Comment by Emmy123222** [comment]
@tupui you can review now

**Review by tupui — APPROVED** [review]
Thanks!

**Comment by Emmy123222** [comment]
Thanks so much @tupui
