### PR TITLE
fix: avoid preselecting vote option

### LINKED ISSUE #105: No default for vote casting
We must not pre-select a voting outcome when casting a vote. Right now we default to the following:

Image

Nothing should be selected.

### PR DESCRIPTION
**Pull request by ComputerOracle**
Fixes issue where a vote option was pre-selected in the voting modal.

The state now initializes as null so no option is selected by default. The checkbox component was updated to explicitly handle null as an unselected state while preserving existing behavior.

This keeps the logic simple and avoids using any workaround values.

closes #105

### CODE REVIEW

File: dapp/src/components/page/proposal/VoteTypeCheckbox.tsx [hunk 1]
```diff
@@ -23,7 +23,11 @@ const VoteTypeCheckbox: FC<Props> = ({
   const width = `${sizeMap[size]}px`,
     height = `${sizeMap[size]}px`;
   const renderIcon = () => {
-    if (voteType == currentVoteType || !currentVoteType) {
+    if (currentVoteType === null) {
+      return <img src="/icons/check-blank.svg" style={{ width, height }} />;
+    }
+
+    if (voteType == currentVoteType || currentVoteType === undefined) {
```
Comment (tupui) [inline dapp/src/components/page/proposal/VoteTypeCheckbox.tsx]: Is it then not enough to just do this?

```suggestion
    if (voteType == currentVoteType) {
```

Why do we check for null and undefined? We are already having a default at the end of the function that returns `check-blank.svg`

**Review by tupui — APPROVED** [review]
That works, thanks!
